version: 1
project:
  name: Customer-Support-CRM
  language: typescript
naming:
  globalSequence: true
tracker:
  type: jira
  project: SCRUM
  workspace: ahmedosamaengineering.atlassian.net
  email: ahmed.osama.engineering@gmail.com

